apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-graphql
  description: GraphQL Backend Plugin
spec:
  type: graphql
  lifecycle: production
  owner: backstage/maintainers
  apiConsumedBy:
    - backstage-demo
  definition:
    $text: https://demo.backstage.io/api/graphql/schema
